import Header from "../(components)/header/page";
import styles from "./tofUse.module.css";
const TermsofUse = () => {
    return ( 
        <div className="main">
            <Header img='/images/TandC.png' header='eEvents Terms of Use' subHeader="Our Terms of Use protect both clients and vendors, ensuring fairness, safety, and transparency on eEvents."/>

            <div>
                <h3 className={styles.header}>Terms and Conditions</h3>
                <p>
                    Risus faucibus duis tincidunt in amet ac blandit. Euismod amet convallis quisque turpis massa arcu laoreet. Convallis morbi egestas nunc non tortor. Ut lorem neque eu libero consequat ornare. Porta dignissim ipsum imperdiet amet libero bibendum. Sed quam tristique elementum dignissim maecenas interdum donec auctor fringilla. Duis augue leo a congue porttitor cursus tincidunt. Non justo integer sollicitudin habitant egestas tortor faucibus lorem turpis. Sollicitudin eu lectus quis malesuada sed eu urna nullam. Hendrerit urna quam mollis libero a. Vel scelerisque ornare leo suspendisse tortor et scelerisque consectetur malesuada. Non nisl turpis id ut orci pellentesque et. Tempus nibh aenean porttitor tristique hendrerit facilisi ac.
                    Dui imperdiet vitae ante tristique gravida. Sed et arcu cras consequat proin. Molestie et urna et eu et. Elit donec egestas tristique platea nunc risus sit placerat malesuada. Lobortis morbi consectetur placerat mi dignissim nulla magna. Platea eget tristique eget at in sed dictumst. Metus diam suspendisse dignissim malesuada laoreet cum nec lectus arcu. At leo amet fermentum pharetra consequat. Facilisis in porttitor massa senectus. Ac purus aliquam nisl sapien amet potenti vivamus eu at. Sit tristique placerat risus fames. Tristique augue in fames elit vitae.
                    Eu pharetra sem malesuada aliquam ut. Lorem diam morbi quam nam maecenas velit suscipit. Commodo sed nisl urna sit purus vestibulum egestas. Nec massa amet fringilla risus. Aliquam vitae nec at aliquet pulvinar tellus massa nunc nisi. Volutpat dui pretium suspendisse vel scelerisque volutpat diam. Id sed tincidunt elementum non fames. Nisi porttitor sit neque ridiculus neque enim ullamcorper nunc leo. Elit congue nibh consectetur nec feugiat.
                    Quam velit odio dictumst lorem feugiat blandit ut etiam amet. In hendrerit est mattis ultricies. Cras ut mauris amet viverra adipiscing elementum tempor elit consectetur. Massa proin tellus pretium tristique nulla eu. Tortor in vitae pretium congue aliquam consequat felis ut. Dui risus sed eget egestas. Eget tortor non accumsan leo. Neque diam orci sagittis proin malesuada nulla malesuada iaculis. Dis in fames adipiscing netus ultrices ac. Ante libero neque tortor lectus. Iaculis porttitor vitae nascetur consectetur neque duis ullamcorper sapien nibh.  
                </p> <br />
                <p style={{fontWeight: '700', color:'#222222'}}>VENDORS ON eEVENTS</p>
                <br />
                <p>
                    Tristique quam interdum sodales vitae. Dolor amet ipsum amet vitae. Enim sapien aliquam arcu consequat amet vestibulum blandit. Sed consequat turpis nunc sit mauris. Mauris a dignissim turpis scelerisque elementum. Pretium vitae neque massa mauris ultricies. Mauris ullamcorper leo aliquet ultrices proin habitasse egestas purus volutpat. Eu egestas ultricies morbi massa. Purus enim ac lorem eget rutrum. Volutpat sodales sapien dictumst scelerisque imperdiet. Cras est nunc duis risus.
                    Porttitor congue gravida arcu tempor. Pulvinar ornare semper eu et viverra ipsum. Eu lectus lacus nunc lectus fringilla suspendisse. Nibh neque odio eu sed tellus tempor eu penatibus leo. Consequat sit fringilla ipsum luctus nunc sapien pellentesque facilisi. Velit congue ullamcorper nunc quam a sit ut. Commodo purus mauris aliquam nam. Consequat quam ac pretium ut turpis quis nisl turpis. Mattis scelerisque pellentesque molestie scelerisque praesent vel.
                    Mauris in amet justo augue. Non a accumsan nullam nam risus consectetur eget. Massa tellus fringilla neque ornare rhoncus sit in nisl. Pulvinar leo posuere egestas tristique ut pretium. Nulla maecenas mattis amet sit suspendisse nisi amet urna. Auctor viverra eleifend arcu luctus. Tristique id massa porttitor leo ac. Malesuada elementum lorem quam consectetur.
                    Nulla leo condimentum duis ornare ultricies quis consectetur est. A fames eget bibendum natoque lacinia sem. Duis habitasse interdum nisl vulputate vulputate at netus. Pellentesque ac diam id massa. Sed a volutpat vulputate vel in integer id magna eget. Egestas dui tellus neque sit elementum mi pellentesque. Vitae ac tempor et malesuada nulla augue. Condimentum pulvinar quam ridiculus sit sed. Elementum nulla mattis varius elementum ullamcorper senectus massa erat hendrerit. Tortor iaculis et adipiscing potenti eu massa. Purus nunc nunc aliquam ac sed magna risus dictum leo. Pretium nunc facilisis rhoncus eleifend sed ut morbi viverra. Porta id eget morbi vestibulum risus massa a. Dui pretium suspendisse magnis massa vitae non. Nec sodales nunc aliquam sagittis nulla proin blandit nunc vel.
                    Quis neque mattis commodo arcu ullamcorper ante pellentesque at. Quisque volutpat tincidunt massa ut. Ullamcorper arcu turpis rhoncus sit amet tortor maecenas. Pretium neque in odio amet tellus pharetra placerat. Elit elit porttitor risus laoreet nibh. Ac vel nunc est malesuada pulvinar non scelerisque aliquam tristique. Id laoreet aliquam nibh egestas.
                    Urna non non faucibus id elementum venenatis. Gravida sed est phasellus commodo cras. Ornare leo id facilisi amet varius egestas vitae molestie sapien. Mauris pharetra sit viverra faucibus et congue aliquet. Tellus sagittis amet fames tristique elit. Risus lectus cursus sit nisl in a massa interdum. Nec dolor magnis justo mollis ut nec morbi turpis. Arcu commodo amet varius purus ornare nam lectus ac. Auctor dictum purus nullam venenatis est interdum felis. Vel amet tincidunt est eu pharetra volutpat. Hendrerit malesuada cursus augue arcu velit ornare. Amet eu sem est sit velit sit gravida faucibus. Blandit fames nam nunc massa gravida mauris sapien congue facilisis.
                    Nisl venenatis diam eleifend tellus. Fringilla est viverra dignissim iaculis semper euismod. Sed vitae risus vitae duis blandit. Egestas cursus scelerisque sit commodo vel convallis. Adipiscing felis mollis porttitor vel. Leo in est ut eget tincidunt blandit libero at. Vulputate integer leo eget pulvinar. Arcu diam scelerisque lectus laoreet integer.
                    Eget ut id tristique velit felis quis elit. Odio scelerisque nisi id ullamcorper mattis tortor. Risus etiam iaculis felis sagittis sem faucibus suspendisse cras eros. Lectus nibh sapien amet egestas nunc. Netus quis cursus dui ut massa nibh mauris. Orci ut tellus tellus dictum. Vitae dolor aliquet curabitur eget laoreet tortor mauris lacus. Viverra ligula blandit iaculis enim. Scelerisque eget sem tortor convallis eu etiam duis fringilla tellus. Amet amet at nulla pharetra. Nulla non ornare pulvinar sem.
                    Donec ullamcorper ipsum sed odio pellentesque massa fermentum ultrices. Nibh malesuada hendrerit facilisi sed ultricies turpis neque. Sed eget ac eu massa imperdiet lectus. Eu ultrices sed fermentum sed sed duis. Nec ultrices euismod lectus pulvinar rhoncus
                </p><br />
                <p style={{fontWeight: '700', color:'#222222'}}>CLIENTS ON eEVENTS</p>
                <br />
                <p>
                    Tristique quam interdum sodales vitae. Dolor amet ipsum amet vitae. Enim sapien aliquam arcu consequat amet vestibulum blandit. Sed consequat turpis nunc sit mauris. Mauris a dignissim turpis scelerisque elementum. Pretium vitae neque massa mauris ultricies. Mauris ullamcorper leo aliquet ultrices proin habitasse egestas purus volutpat. Eu egestas ultricies morbi massa. Purus enim ac lorem eget rutrum. Volutpat sodales sapien dictumst scelerisque imperdiet. Cras est nunc duis risus.
                    Porttitor congue gravida arcu tempor. Pulvinar ornare semper eu et viverra ipsum. Eu lectus lacus nunc lectus fringilla suspendisse. Nibh neque odio eu sed tellus tempor eu penatibus leo. Consequat sit fringilla ipsum luctus nunc sapien pellentesque facilisi. Velit congue ullamcorper nunc quam a sit ut. Commodo purus mauris aliquam nam. Consequat quam ac pretium ut turpis quis nisl turpis. Mattis scelerisque pellentesque molestie scelerisque praesent vel.
                    Mauris in amet justo augue. Non a accumsan nullam nam risus consectetur eget. Massa tellus fringilla neque ornare rhoncus sit in nisl. Pulvinar leo posuere egestas tristique ut pretium. Nulla maecenas mattis amet sit suspendisse nisi amet urna. Auctor viverra eleifend arcu luctus. Tristique id massa porttitor leo ac. Malesuada elementum lorem quam consectetur.
                    Nulla leo condimentum duis ornare ultricies quis consectetur est. A fames eget bibendum natoque lacinia sem. Duis habitasse interdum nisl vulputate vulputate at netus. Pellentesque ac diam id massa. Sed a volutpat vulputate vel in integer id magna eget. Egestas dui tellus neque sit elementum mi pellentesque. Vitae ac tempor et malesuada nulla augue. Condimentum pulvinar quam ridiculus sit sed. Elementum nulla mattis varius elementum ullamcorper senectus massa erat hendrerit. Tortor iaculis et adipiscing potenti eu massa. Purus nunc nunc aliquam ac sed magna risus dictum leo. Pretium nunc facilisis rhoncus eleifend sed ut morbi viverra. Porta id eget morbi vestibulum risus massa a. Dui pretium suspendisse magnis massa vitae non. Nec sodales nunc aliquam sagittis nulla proin blandit nunc vel.
                    Quis neque mattis commodo arcu ullamcorper ante pellentesque at. Quisque volutpat tincidunt massa ut. Ullamcorper arcu turpis rhoncus sit amet tortor maecenas. Pretium neque in odio amet tellus pharetra placerat. Elit elit porttitor risus laoreet nibh. Ac vel nunc est malesuada pulvinar non scelerisque aliquam tristique. Id laoreet aliquam nibh egestas.
                    Urna non non faucibus id elementum venenatis. Gravida sed est phasellus commodo cras. Ornare leo id facilisi amet varius egestas vitae molestie sapien. Mauris pharetra sit viverra faucibus et congue aliquet. Tellus sagittis amet fames tristique elit. Risus lectus cursus sit nisl in a massa interdum. Nec dolor magnis justo mollis ut nec morbi turpis. Arcu commodo amet varius purus ornare nam lectus ac. Auctor dictum purus nullam venenatis est interdum felis. Vel amet tincidunt est eu pharetra volutpat. Hendrerit malesuada cursus augue arcu velit ornare. Amet eu sem est sit velit sit gravida faucibus. Blandit fames nam nunc massa gravida mauris sapien congue facilisis.
                    Nisl venenatis diam eleifend tellus. Fringilla est viverra dignissim iaculis semper euismod. Sed vitae risus vitae duis blandit. Egestas cursus scelerisque sit commodo vel convallis. Adipiscing felis mollis porttitor vel. Leo in est ut eget tincidunt blandit libero at. Vulputate integer leo eget pulvinar. Arcu diam scelerisque lectus laoreet integer.
                    Eget ut id tristique velit felis quis elit. Odio scelerisque nisi id ullamcorper mattis tortor. Risus etiam iaculis felis sagittis sem faucibus suspendisse cras eros. Lectus nibh sapien amet egestas nunc. Netus quis cursus dui ut massa nibh mauris. Orci ut tellus tellus dictum. Vitae dolor aliquet curabitur eget laoreet tortor mauris lacus. Viverra ligula blandit iaculis enim. Scelerisque eget sem tortor convallis eu etiam duis fringilla tellus. Amet amet at nulla pharetra. Nulla non ornare pulvinar sem.
                    Donec ullamcorper ipsum sed odio pellentesque massa fermentum ultrices. Nibh malesuada hendrerit facilisi sed ultricies turpis neque. Sed eget ac eu massa imperdiet lectus. Eu ultrices sed fermentum sed sed duis. Nec ultrices euismod lectus pulvinar rhoncus
                </p>
            </div>
        
        </div>
    );
}
 
export default TermsofUse;